---
- name: Update repository indexes
  ansible.builtin.apt:
    update_cache: true
  when: apt_update
  tags:
    - update

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: dist
  when: apt_upgrade
  tags:
    - upgrade
    - dist-upgrade

- name: List packages to install
  ansible.builtin.debug:
    msg: "{{ apt_install | join(',') }}"
  tags:
    - install
    - debug

- name: Install specified packages
  ansible.builtin.apt:
    name: "{{ apt_install }}"
    state: present
  tags:
    - install

- name: List packages to remove
  ansible.builtin.debug:
    msg: "{{ apt_remove | join(',') }}"
  tags:
    - remove
    - debug

- name: Remove specified packages
  ansible.builtin.apt:
    name: "{{ apt_remove }}"
    state: absent
    purge: "{{ apt_remove_purge }}"
  tags:
    - remove

- name: Remove redundant and unused packages
  ansible.builtin.apt:
    autoremove: true
  when: apt_autoremove
  tags:
    - autoremove
