---
- name: Update APT indexes
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 0 if apt_config_updated is defined and apt_config_updated.changed else apt_update_cache_valid_time }}"
  when: apt_update
  tags: [apt, update]
   
- name: Run 'dpkg --configure -a'
  ansible.builtin.command: >
    dpkg --configure -a
  args:
    warn: false
  changed_when: _dpkg_configure.stdout_lines | length > 0
  register: _dpkg_configure
  when: apt_dpkg_configure
  tags: [apt, dpkg, configure]

- name: Install APT dependencies
  ansible.builtin.apt:
    name: "{{ apt_dependencies }}"
    state: "{{ apt_install_state }}"
  tags: [apt, dependencies]
    
- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_type }}"
    update_cache: true
    dpkg_options: "{{ apt_upgrade_dpkg_options | join(',') }}"
  when: apt_upgrade
  tags: [apt, upgrade]

- name: Cleanup packages
  ansible.builtin.command: >
    apt-get -y clean
  args:
    warn: false
  changed_when: false
  when: apt_clean
  tags: [apt, clean]
  
- name: Debug - Packages to install
  ansible.builtin.debug:
    msg: "{{ apt_install | join(',') }}"
  tags: [apt, install, debug]

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_install }}"
    state: "{{ apt_install_state }}"
  tags: [apt, install, packages]

- name: Debug - Packages to remove
  ansible.builtin.debug:
    msg: "{{ apt_remove | join(',') }}"
  tags: [apt, remove, debug]
    
- name: Remove packages
  ansible.builtin.apt:
    name: "{{ apt_remove }}"
    state: absent
    purge: "{{ apt_remove_purge }}"
  tags: [apt, remove, packages]
    
- name: Autoremove packages
  ansible.builtin.apt:
    autoremove: true
    dpkg_options: "{{ apt_upgrade_dpkg_options | join(',') }}"
  when: apt_autoremove
  tags: [apt, autoremove]
